name: Build and Deploy to ACR

on:
  push:
    branches:
      - main  # or the branch you want to trigger the pipeline on

env:
  K8S_MANIFESTS_DIR: k8s-manifest  

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}  # Set commit SHA as an environment variable

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry (ACR)
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker image with BuildKit
        run: |
          DOCKER_BUILDKIT=1 docker build --build-arg BUILDKIT_INLINE_CACHE=1 -t ${{ secrets.ACR_NAME }}.azurecr.io/my-image:${{ env.COMMIT_SHA }} .

      - name: Push Docker Image to ACR
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/my-image:${{ env.COMMIT_SHA }}

      - name: Logout from ACR
        run: docker logout ${{ secrets.ACR_NAME }}.azurecr.io

        - name: Update Kubernetes Manifests with New Image Tags
        run: |
          for FILE in ${K8S_MANIFESTS_DIR}/*.yaml; do
            # Replace the image tag in the YAML file
            sed -i "s|\(image: [^:]*\)|image: ${ACR_NAME}.azurecr.io/my-image:${{ env.COMMIT_SHA }}|g" "$FILE"
          done
          echo "✅ The following Kubernetes manifests have been updated with COMMIT_SHA:"
          grep -H "image:" ${K8S_MANIFESTS_DIR}/*.yaml
      
          echo "🚀 Applying updated manifests to AKS..."
          kubectl apply -f ${K8S_MANIFESTS_DIR}
      
