name: Build and Deploy to ACR

on:
  push:
    branches:
      - main  # or the branch you want to trigger the pipeline on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: testrepo3.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t testrepo3.azurecr.io/react-app:latest .
          docker push testrepo3.azurecr.io/react-app:latest

      - name: Logout from ACR
        run: docker logout testrepo3.azurecr.io
