apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: argo1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: testrepo3.azurecr.io/my-image:${COMMIT_SHA}  # This will be updated correctly by GitHub Actions
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: acr-auth